### ISSUE TITLE
before text required

### ISSUE THREAD

**Issue by treestonemedia** [meyerauslander/My-Zmanim-Wordpress-Widget#10]
@meyerauslander 

When using this for the first time, if you don't choose a `before text` and `after text` it throws an error `Undefined index: in /wp-content/plugins/My-Zmanim-Wordpress-Widget-master/my-zmanim-widget.php on line 142`

**Comment by meyerauslander** [comment]
Chaim, I think I fixed this error.  I'm not sure because my version of php
does not cause the same exact problem.  I did not yet start working on the
plug-in for SB.  I want to start as soon as possible but I'm not yet at a
good stopping point in what I'm doing in the My-Zmanim widget.  I'm half
way through implementing the "delete transients" option.  Is it ok if I
finish it up first?  Thanks,

Meyer
